/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
  3: 1,3
   6: 1,2,3,6
   10: 1,2,5,10
   15: 1,3,5,15
   21: 1,3,7,21
   28: 1,2,4,7,14,28
   We can see that 28 is the first triangle number to have over five divisors.

   What is the value of the first triangle number to have over five hundred divisors?
*/

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;

class Twelve {
  public static void main(String[] args) {
    for (int n: triangleNumbers) {
      if (Primes.factors(n).size() > 500) {
        System.out.println(n);
	return;
      }
    }
  }

  static final Iterable<Integer> triangleNumbers = new Iterable<Integer>() {
    public Iterator<Integer> iterator() {
      return new Iterator<Integer>() {
        int sum = 0, i = 0;
        public boolean hasNext() {
	  return true;
	}

	public void remove() {
	  throw new NoSuchElementException();
	}

	public Integer next() {
	  return sum += ++i;
	}
      };
    }
  };

}
