/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/
class Two {
  public static void main(String[] args) {
    int previous = 1;
    int tmp;
    int sum = 0;
    for (int a = 2; a <= 4000000; tmp = a, a += previous, previous = tmp)
      if (a % 2 == 0)
        sum += a;
    System.out.println(sum);
  }
}
